### ISSUE TITLE
Source of the gitbook?

### ISSUE THREAD

**Issue by waldyrious** [hzhou/MyDef#1]
I started reading the [mydef gitbook](https://huizhou.gitbooks.io/programming-with-mydef/) and found a couple passages I'd like to submit edits for, but I couldn't figure out where the source of that book is located. Can you give me a pointer?

**Comment by hzhou** [comment]
https://git.gitbook.com/huizhou/programming-with-mydef.git

**Comment by waldyrious** [comment]
So there isn't a web interface for the gitbook repo where one could submit issues, PRs, etc?

**Comment by hzhou** [comment]
There is a disucssions page on https://www.gitbook.com/book/huizhou/programming-with-mydef/details, right?

**Comment by waldyrious** [comment]
I see. I suppose that can stand in for issues, but not pull requests. This appears to be a limitation of gitbook itself, although they seem to be considering the possibility of implementing such a workflow.

In the meantime, would you consider hosting a mirror of that git repo here on github so people could propose changes directly?

**Comment by hzhou** [comment]
Here it is: https://github.com/hzhou/MyDef_Book

**Comment by waldyrious** [comment]
Awesome, thanks for the swift reaction! 🎉 😄
