### ISSUE TITLE
installation result does not match instructions

### ISSUE THREAD

**Issue by daxim** [hzhou/MyDef#2]
Following https://huizhou.gitbooks.io/programming-with-mydef/content/Installing.html

    daxim@rotechili:~/hack/MyDef› git rev-parse HEAD
    ce2db2c8f703138ac2981c8e93291d1197fc2a04
    daxim@rotechili:~/hack/MyDef› which perl
    /home/daxim/local/share/perlbrew/perls/perl-5.24.1/bin/perl

    # set required env vars
    daxim@rotechili:~/hack/MyDef› export PATH=/home/daxim/local/bin:/home/daxim/local/share/perlbrew/bin:/home/daxim/local/share/perlbrew/perls/perl-5.24.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
    daxim@rotechili:~/hack/MyDef› export MYDEFLIB=/tmp/mydeftest
    daxim@rotechili:~/hack/MyDef› export PERL5LIB=/tmp/perl5

    # ensure clean state
    daxim@rotechili:~/hack/MyDef› rm -rf /home/daxim/local/bin/mydef_*
    daxim@rotechili:~/hack/MyDef› rm -rf /tmp/mydeftest
    daxim@rotechili:~/hack/MyDef› rm -rf /tmp/perl5

    # kick off installation
    daxim@rotechili:~/hack/MyDef› yes | sh bootstrap.sh

    #---- Install from bootstrap ----
    This will install script into your leading path: [/home/daxim/local/bin]
      press 'y' to continute (abort otherwise)
    install_all: /home/daxim/local/bin [-]
      :| mydef_debug -> /home/daxim/local/bin/mydef_debug
      :| mydef_install -> /home/daxim/local/bin/mydef_install
      :| mydef_make -> /home/daxim/local/bin/mydef_make
      :| mydef_page -> /home/daxim/local/bin/mydef_page
      :| mydef_run -> /home/daxim/local/bin/mydef_run
    install_all: /tmp/perl5 [pm]
      :| MyDef.pm -> /tmp/perl5/MyDef.pm
      :| MyDef/compileutil.pm -> /tmp/perl5/MyDef/compileutil.pm
      :| MyDef/dumpout.pm -> /tmp/perl5/MyDef/dumpout.pm
      :| MyDef/output_general.pm -> /tmp/perl5/MyDef/output_general.pm
      :| MyDef/output_perl.pm -> /tmp/perl5/MyDef/output_perl.pm
      :| MyDef/parseutil.pm -> /tmp/perl5/MyDef/parseutil.pm
      :| MyDef/utils.pm -> /tmp/perl5/MyDef/utils.pm
    install_all: /tmp/mydeftest [def]
      :| std_general.def -> /tmp/mydeftest/std_general.def
      :| std_perl.def -> /tmp/mydeftest/std_perl.def
    install_all: /tmp/mydeftest [def]
      :| ansi_color.def -> /tmp/mydeftest/ansi_color.def
      :| constants.def -> /tmp/mydeftest/constants.def
      :| DefParser.def -> /tmp/mydeftest/DefParser.def
      :| ext.def -> /tmp/mydeftest/ext.def
      :| ios_cg.def -> /tmp/mydeftest/ios_cg.def
      :| ios_gl.def -> /tmp/mydeftest/ios_gl.def
      :| ref_counting.def -> /tmp/mydeftest/ref_counting.def
      :| std_apple.def -> /tmp/mydeftest/std_apple.def
      :| std_general.def -> /tmp/mydeftest/std_general.def
      :| std_make.def -> /tmp/mydeftest/std_make.def
      :| std_perl.def -> /tmp/mydeftest/std_perl.def
      :| DefParser/ast.def -> /tmp/mydeftest/DefParser/ast.def
      :| DefParser/c_fifo.def -> /tmp/mydeftest/DefParser/c_fifo.def
      :| DefParser/input_buffer.def -> /tmp/mydeftest/DefParser/input_buffer.def
      :| DefParser/lex.def -> /tmp/mydeftest/DefParser/lex.def
      :| DefParser/parser.def -> /tmp/mydeftest/DefParser/parser.def
      :| perl/apl.def -> /tmp/mydeftest/perl/apl.def
      :| perl/gnuplot.def -> /tmp/mydeftest/perl/gnuplot.def
      :| perl/html.def -> /tmp/mydeftest/perl/html.def
      :| perl/indentations.def -> /tmp/mydeftest/perl/indentations.def
      :| perl/parse.def -> /tmp/mydeftest/perl/parse.def
      :| perl/parse_frame_full.def -> /tmp/mydeftest/perl/parse_frame_full.def
      :| perl/parse_utils.def -> /tmp/mydeftest/perl/parse_utils.def
      :| perl/permutation.def -> /tmp/mydeftest/perl/permutation.def
    
    #---- Compile from fresh MyDef source ----
        output_dir: MyDef
        Skip folder bootstrap
        Skip folder deflib
        Skip folder docs
        Skip folder macros_compile
        Skip folder macros_make
        Skip folder macros_output
        Skip folder macros_parse
        Skip folder macros_util
        Skip folder old
        Skip folder tests
    custom_run.def not found
      search path: /tmp/mydeftest
    mydef_page parseutil.def MyDef/lib/MyDef/parseutil.pm
    PAGE: parseutil
      --> [MyDef/lib/MyDef/parseutil.pm]
    mydef_page output_perl.def MyDef/lib/MyDef/output_perl.pm
    PAGE: output_perl
      --> [MyDef/lib/MyDef/output_perl.pm]
    mydef_page output_general.def MyDef/lib/MyDef/output_general.pm
    PAGE: output_general
      --> [MyDef/lib/MyDef/output_general.pm]
    mydef_page mydef_utils.def MyDef/lib/MyDef/utils.pm
    PAGE: utils
      --> [MyDef/lib/MyDef/utils.pm]
    mydef_page mydef_ext.def MyDef/lib/MyDef/ext.pm
    PAGE: ext
      --> [MyDef/lib/MyDef/ext.pm]
    mydef_page dumpout.def MyDef/lib/MyDef/dumpout.pm
    PAGE: dumpout
      --> [MyDef/lib/MyDef/dumpout.pm]
    mydef_page compileutil.def MyDef/lib/MyDef/compileutil.pm
    PAGE: compileutil
      --> [MyDef/lib/MyDef/compileutil.pm]
    mydef_page mydef.def MyDef/lib/MyDef.pm
    PAGE: MyDef
      --> [MyDef/lib/MyDef.pm]
    mydef_page mydef_update.def MyDef/script/mydef_update
    PAGE: mydef_update
      --> [MyDef/script/mydef_update]
    mydef_page mydef_run.def MyDef/script/mydef_run
    PAGE: mydef_run
      --> [MyDef/script/mydef_run]
    mydef_page mydef_page.def MyDef/script/mydef_page
    PAGE: mydef_page
      --> [MyDef/script/mydef_page]
    mydef_page mydef_make.def MyDef/script/mydef_make
    PAGE: mydef_make
      --> [MyDef/script/mydef_make]
    mydef_page mydef_install.def MyDef/script/mydef_install
    PAGE: mydef_install
      --> [MyDef/script/mydef_install]
    mydef_page mydef_decl.def MyDef/script/mydef_decl
    PAGE: mydef_decl
      --> [MyDef/script/mydef_decl]
    mydef_page mydef_debug.def MyDef/script/mydef_debug
    PAGE: mydef_debug
      --> [MyDef/script/mydef_debug]
    
    #---- Install updated MyDef ----
    install_all: /tmp/perl5 [pm]
      :| MyDef.pm -> /tmp/perl5/MyDef.pm
      :| MyDef/compileutil.pm -> /tmp/perl5/MyDef/compileutil.pm
      :| MyDef/dumpout.pm -> /tmp/perl5/MyDef/dumpout.pm
      :| MyDef/ext.pm -> /tmp/perl5/MyDef/ext.pm
      :| MyDef/output_general.pm -> /tmp/perl5/MyDef/output_general.pm
      :| MyDef/output_perl.pm -> /tmp/perl5/MyDef/output_perl.pm
      :| MyDef/parseutil.pm -> /tmp/perl5/MyDef/parseutil.pm
      :| MyDef/utils.pm -> /tmp/perl5/MyDef/utils.pm
    This will install script into your leading path: [/home/daxim/local/bin]
      press 'y' to continute (abort otherwise)
    install_all: /home/daxim/local/bin [-]
      :| mydef_debug -> /home/daxim/local/bin/mydef_debug
      :| mydef_decl -> /home/daxim/local/bin/mydef_decl
      :| mydef_install -> /home/daxim/local/bin/mydef_install
      :| mydef_make -> /home/daxim/local/bin/mydef_make
      :| mydef_page -> /home/daxim/local/bin/mydef_page
      :| mydef_run -> /home/daxim/local/bin/mydef_run
      :| mydef_update -> /home/daxim/local/bin/mydef_update
    daxim@rotechili:~/hack/MyDef› cd /tmp
    daxim@rotechili:/tmp› tree mydeftest perl5
    mydeftest
    ├── ansi_color.def
    ├── constants.def
    ├── DefParser
    │   ├── ast.def
    │   ├── c_fifo.def
    │   ├── input_buffer.def
    │   ├── lex.def
    │   └── parser.def
    ├── DefParser.def
    ├── ext.def
    ├── ios_cg.def
    ├── ios_gl.def
    ├── perl
    │   ├── apl.def
    │   ├── gnuplot.def
    │   ├── html.def
    │   ├── indentations.def
    │   ├── parse.def
    │   ├── parse_frame_full.def
    │   ├── parse_utils.def
    │   └── permutation.def
    ├── ref_counting.def
    ├── std_apple.def
    ├── std_general.def
    ├── std_make.def
    └── std_perl.def
    perl5
    ├── MyDef
    │   ├── compileutil.pm
    │   ├── dumpout.pm
    │   ├── ext.pm
    │   ├── output_general.pm
    │   ├── output_perl.pm
    │   ├── parseutil.pm
    │   └── utils.pm
    └── MyDef.pm

    3 directories, 32 files
    daxim@rotechili:/tmp› $EDITOR test.def
    daxim@rotechili:/tmp› cat test.def
    page: test, basic_frame
        $print Hello world!
    daxim@rotechili:/tmp› mydef_page -mperl test.def
    PAGE: test
    [:] Code basic_frame not found!
      --> [./test.pl]
    daxim@rotechili:/tmp› cat test.pl
    #!/usr/bin/perl
    use strict;

Note the error message from `mydef_page` and the lack of print statement in the output code.

**Comment by hzhou** [comment]
Try this: 

```
    page: test
        $print Hello world!
```

`page: test, basic_frame` looks for a subcode basic_frame as main code. It is convenient for C and Java etc, but for Perl, it is not necessary, thus absent, resulting in a empty output. 

I'll fix the instructions soon.

**Comment by hzhou** [comment]
I made the quick fix on gitbook. Although the book is still good on principle, it is quite outdated. There are more inconsistencies. I'll fix and fill in more details as long as there is feedback.

**Comment by daxim** [comment]
Last paragraph on `Installing.html` is not working as intended:

    › mydef_run test.def
    PAGE: test
      --> [./test.txt]
    do not know how to run it

This works:

    › mydef_run -mperl test.def
    PAGE: test
      --> [./test.pl]
    perl ./test.pl
    Hello world!

**Comment by hzhou** [comment]
Thanks. I have fixed it, as well as expanded and separated the quick tutorial into a new section.
